-- ============================================================
-- Smart Farm IoT System — Supabase Database Schema
-- Run this script in your Supabase SQL Editor (https://supabase.com/dashboard/project/exnhqpzlkucjiubvsabx/sql)
-- ============================================================

-- 1. Sensor Readings Table (Logged periodically, e.g. every 60s)
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    temperature NUMERIC,
    humidity NUMERIC,
    soil_moisture INT,
    soil_raw INT,
    tank_full BOOLEAN,
    pump_state BOOLEAN,
    auto_mode BOOLEAN,
    alerts TEXT[]
);

-- 2. Pump Events Table (Logged on every pump state change)
CREATE TABLE IF NOT EXISTS public.pump_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    event_type TEXT NOT NULL, -- e.g., 'manual_on', 'manual_off', 'auto_on', 'auto_off', 'safety_off'
    pump_state BOOLEAN NOT NULL,
    triggered_by TEXT DEFAULT 'user'
);

-- 3. System Alerts Log Table (Logged when alerts trigger/change)
CREATE TABLE IF NOT EXISTS public.alerts_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    alert_count INT NOT NULL,
    alerts TEXT[] NOT NULL
);

-- ------------------------------------------------------------
-- Row Level Security (RLS) Policies
-- Ensures only authenticated users (logged-in dashboard users) can read/write data
-- ------------------------------------------------------------

-- Enable RLS
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pump_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts_log ENABLE ROW LEVEL SECURITY;

-- Create Policies for Authenticated Users
CREATE POLICY "Allow authenticated read/write on sensor_readings"
    ON public.sensor_readings
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow authenticated read/write on pump_events"
    ON public.pump_events
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow authenticated read/write on alerts_log"
    ON public.alerts_log
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
